admin:
  email: insfocus@gmail.com
  full_name: admin
caowendong:
  email: caowending@huawei.com
  full_name: caowendong
chenqi:
  email: chenqi163@h-partners.com
  full_name: chenqi
chenyang:
  email: 775517776@qq.com
  full_name: chenyang
gongzhuangbang:
  email: gongzhuangbang1@huawei.com
  full_name: gongzhuangbang
hanszheng:
  email: zhengyuhang@huawei.com
  full_name: hansZheng
heguofeng:
  email: heguofeng@huawei.com
  full_name: heguofeng
jenkins_read:
  email: tommylikehu@gmail.com
  full_name: infrastructure read user
luonan:
  email: luonan7@h-partnets.com
  full_name: luonan
luweitao:
  email: luweitao2@h-partners.com
  full_name: luweitao
mindspore_slave:
  email: zhengweimin1@huawei.com
  full_name: mindspore_slave
radiaTest:
  email: zhangyizheng3@huawei.com
  full_name: radiaTest
read:
  email: 15040638030@163.com
  full_name: read
test_001:
  email: tommylikehu@gmail.com
  full_name: test_001
trigger:
  email: george.cao@huawei.com
  full_name: trigger
wangting:
  email: kathy.wangting@huawei.com
  full_name: wangting
wangzhigang:
  email: wangzhigang35@huawei.com
  full_name: wangzhigang
wucaiping:
  email: wucaiping@h-partners.com
  full_name: wucaiping
xiaozhongqi:
  email: xiaozhongqi@huawei.com
  full_name: xiaozhongqi
xihe:
  email: zhouzixian@h-partners.com
  full_name: xihe
yangcong:
  email: yangcong11@huawei.com
  full_name: yangcong
yuchunao:
  email: yuchunao@h-partners.com
  full_name: yuchunao
yujiwen:
  email: yujiwen
  full_name: yujiwen
zhaojiaming:
  email: zhaojiaming6@h-partners.com
  full_name: zhaojiaming
zhuchao:
  email: zhuchao50@h-partners.com
  full_name: zhuchao
